Root    ::= Stmt
        <$>

Stmt    ::= Fact Stmt'
        <$>

Stmt'   ::= epsilon
        <+> , Fact Stmt'
        <$>

Fact    ::= epsilon
        <+> Id Annot Fact'
        <+> module Id { Stmt }
        <$>

Fact'   ::= epsilon
        <+> = Exp6
        <$>

Exp1    ::= Id Extract
        <+> RtoL Exp1
        <+> Number
        <+> Bool
        <+> ( Exp6 )
        <+> { }
        <$>

Exp2    ::= Exp1 Exp2' <$>
Exp3    ::= Exp2 Exp3' <$>
Exp4    ::= Exp3 Exp4' <$>
Exp5    ::= Exp4 Exp5' <$>
Exp6    ::= Exp5 Exp6' <$>

Exp2'   ::= epsilon <+> Op2 Exp1 Exp2' <$>
Exp3'   ::= epsilon <+> Op3 Exp2 Exp3' <$>
Exp4'   ::= epsilon <+> Op4 Exp3 Exp4' <$>
Exp5'   ::= epsilon <+> Op5 Exp4 Exp5' <$>
Exp6'   ::= epsilon <+> Op6 Exp5 Exp6' <$>

RtoL    ::= ! <+> - <$>

Op2     ::= * <+> / <$>

Op3     ::= + <+> - <$>

Op4     ::= > <+> >= <+> < <+> <= <$>

Op5     ::= == <+> != <$>

Op6     ::= | <+> || <+> & <+> && <$>

Extract ::= epsilon
        <+> : Id ( Stmt ) Extract
        <$>

Annot   ::= epsilon
        <+> : Exp1
        <$>
